// export const CHARAKTERS = 'Charakters';
// export const EPİSODES = 'Episodes';
// export const LOCATIONS = 'Locations';
// export const SETTINGS = 'Settings';
// export const TABNAVIGATOR = 'TabNavigator';
const CHARAKTERS = 'Charakters';
const EPİSODES = 'Episodes';
const LOCATIONS = 'Locations';
const SETTINGS = 'Settings';
const TABNAVIGATOR = 'TabNavigator';
export {CHARAKTERS, EPİSODES, LOCATIONS, SETTINGS, TABNAVIGATOR};
